[package]
name = "postprocess"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.3"
rand = "0.9.1"
stacker = "0.1.21"

[dependencies.image]
version = "0.25.2"
default-features = false
features = ["png", "jpeg"]
